#!/usr/bin/env bash

set -euo pipefail
readonly IFS=$'\n\t'

readonly FUNCTIONS="$PWD/ci/support/functions.sh"

# Load colours and common functions
chmod +x "$FUNCTIONS"
# shellcheck source=/dev/null
source "$FUNCTIONS"

readonly NULLSHA="0000000000000000000000000000000000000000"

# File size limits
readonly MAXSIZE=2000000 # 2mb
readonly MAXSIZE_mb=$((MAXSIZE / 1000000))

# Read stdin for ref information
while read -r oldref newref refname; do
    print_info "Refs: $oldref $newref $refname"
    
    if [ "${newref}" = "${NULLSHA}" ]
    then
        oldref="HEAD"
    fi

    # Check file sizes and reject any files too big
    print_info "Maxiumum file size is ${MAXSIZE_mb}mb"
    for file in $(git diff --stat --name-only --diff-filter=AM "${oldref}"..."${newref}"); do
        # Check file size
        size_bytes=$(git cat-file -s "${newref}":"${file}")
        size_mb=$((size_bytes / 1000000))
        print_info "${file}: file size is ${size_mb}mb"
        if [ "$size_bytes" -gt "$MAXSIZE" ]
        then 
            print_error "${file}: File size is too big to push, track with LFS"
            print_info "https://www.atlassian.com/git/tutorials/git-lfs"
            continue 
        fi
            done
done
